#!/usr/bin/env python3
"""Generate the synthetic run records the analysis pipeline is tested against (task SSY-05).

SYNTHETIC TEST DATA — NOT EVIDENCE. Nothing here was measured. Every value is produced by a
closed-form generator so that the correct answer is known before the pipeline runs, which is the
only way to tell a pipeline that works from one that merely produces numbers.

Four cases:
  positive       power depends on seam count beyond mean clearance; a defect-aware model should
                 beat the mean-only baseline on a held-out seam configuration
  null           power depends on mean clearance alone; the defect-aware model should NOT improve
  missing-data   a walled sample carries no clearance value
  unit-error     the clearance channel is declared in millimetres
"""
import argparse, hashlib, json, math, shutil
from pathlib import Path

LABEL = "SYNTHETIC TEST DATA - NOT EVIDENCE. Generated by scripts/make_synthetic_fixtures.py."
UNITS = {"c_um": "um", "thrust_N": "N", "voltage_V": "V", "current_A": "A", "rpm": "rpm"}
N_THETA, N_SAMPLES = 72, 40


def clearance_field(c_bar, lobe_a, lobe_phase_deg, n_seams, seam_width_deg, step_um):
    """Wall-domain clearance with seams as absent wall, built to be equal-mean by construction."""
    theta, c_vals, mask = [], [], []
    seam_centres = [i * 360.0 / n_seams for i in range(n_seams)] if n_seams else []
    segment_offsets = [((-1) ** j) * step_um / 2.0 for j in range(max(n_seams, 1))]
    if n_seams and n_seams % 2:                      # odd count: solve so the offsets sum to zero
        bias = sum(segment_offsets) / n_seams
        segment_offsets = [d - bias for d in segment_offsets]
    for k in range(N_THETA):
        t = k * 360.0 / N_THETA
        in_seam = any(min(abs(t - cc), 360 - abs(t - cc)) < seam_width_deg / 2.0 for cc in seam_centres)
        theta.append(t)
        if in_seam:
            c_vals.append(None); mask.append(False); continue
        seg = 0
        if n_seams:
            ahead = [(cc - t) % 360.0 for cc in seam_centres]
            seg = min(range(n_seams), key=lambda i: ahead[i])
        value = (c_bar + lobe_a * math.cos(2 * math.radians(t - lobe_phase_deg))
                 + segment_offsets[seg % len(segment_offsets)])
        c_vals.append(value); mask.append(True)
    return dict(theta_deg=theta, c_um=c_vals, wall_mask=mask)


def run_record(study, specimen, cycle, run_id, family, config_group, c_bar, lobe_a, n_seams,
               seam_width, step_um, thrust_N, power_W, rpm=6000.0):
    """One run at one operating point. Voltage and current are synthesised to hit power_W."""
    voltage = 14.8
    current = power_W / voltage
    return {
        "schema_version": 1,
        "evidence_state": LABEL,
        "study_id": study, "specimen_id": specimen, "deployment_cycle": cycle, "run_id": run_id,
        "condition": dict(family=family, config_group=config_group, n_seams=n_seams,
                          seam_width_deg=seam_width, step_um=step_um,
                          lobe_amplitude_um=lobe_a, lobe_phase_deg=0.0),
        "units": dict(UNITS),
        "clearance_field": clearance_field(c_bar, lobe_a, 0.0, n_seams, seam_width, step_um),
        "channels": {
            "t_s": [i * 0.01 for i in range(N_SAMPLES)],
            "thrust_N": [thrust_N] * N_SAMPLES,
            "voltage_V": [voltage] * N_SAMPLES,
            "current_A": [current] * N_SAMPLES,
            "rpm": [rpm] * N_SAMPLES,
        },
    }


def jitter(*key, scale):
    """Deterministic pseudo-random offset in [-scale, +scale], reproducible without a dependency.

    Real specimens differ from one another and real runs scatter. Noiseless fixtures make every
    specimen identical, which drives the spread across specimens to exactly zero and hides whether
    the uncertainty machinery works at all.
    """
    h = hashlib.sha256("|".join(map(str, key)).encode()).digest()
    return (int.from_bytes(h[:8], "big") / 2 ** 64 - 0.5) * 2.0 * scale


def power_model(c_bar, n_seams, total_opening, seam_sensitive):
    """Closed form. Seam COUNT and total OPENING are separate terms so a test can tell them apart."""
    p = 60.0 + 0.010 * (c_bar - 1000.0)
    if seam_sensitive:
        p += 1.8 * n_seams + 0.05 * total_opening
    return p


# Conditions for the equal-mean design the project actually proposes: one target mean clearance
# throughout, with seam count and individual width varied INDEPENDENTLY so that count and total
# opening are not confounded. Four of the seam rows share a total opening of 24 degrees while
# their count varies, which is the fixed-opening redistribution contrast; two more vary width at
# fixed count, which is the fixed-count contrast.
EQUAL_MEAN_CONDITIONS = [
    ("uniform",  "uniform",   0.0, 0, 0.0,  0.0),
    ("two_lobe", "lobe_a40", 40.0, 0, 0.0,  0.0),
    ("two_lobe", "lobe_a80", 80.0, 0, 0.0,  0.0),
    ("seam", "seam_n2_w12",   0.0, 2, 12.0, 20.0),
    ("seam", "seam_n3_w8",    0.0, 3,  8.0, 20.0),
    ("seam", "seam_n4_w6",    0.0, 4,  6.0, 20.0),
    ("seam", "seam_n6_w4",    0.0, 6,  4.0, 20.0),
    ("seam", "seam_n3_w6",    0.0, 3,  6.0, 20.0),
    ("seam", "seam_n3_w12",   0.0, 3, 12.0, 20.0),
]
C_BAR_TARGET = 1000.0
SPECIMENS_PER_CONDITION = 4


def build_case(out, seam_sensitive, equal_mean=True, noise_W=0.35, effect_scale=1.0):
    """Each condition is built on more than one specimen, so specimen-first scoring is exercised
    and a split can be checked for specimen disjointness."""
    files = 0
    for ci, (family, group, lobe, n_seams, width, step) in enumerate(EQUAL_MEAN_CONDITIONS):
        c_bar = C_BAR_TARGET if equal_mean else C_BAR_TARGET + 10.0 * ci
        total_opening = n_seams * width
        base = power_model(c_bar, n_seams, total_opening, seam_sensitive) * effect_scale
        for si in range(SPECIMENS_PER_CONDITION):
            specimen = f"SPEC-{ci:02d}{chr(ord('A') + si)}"
            spec_offset = jitter(group, specimen, scale=noise_W)
            for ti, thrust in enumerate((3.0, 4.0, 5.0)):
                power = base * (0.8 + 0.1 * ti) + spec_offset + jitter(specimen, ti, scale=noise_W / 4)
                rec = run_record("SSY-SYNTH", specimen, 1, f"R{ci:02d}{si}-{ti}", family, group,
                                 c_bar, lobe, n_seams, width, step,
                                 thrust_N=thrust, power_W=power)
                (out / f"{specimen}_{rec['run_id']}.json").write_text(
                    json.dumps(rec, indent=1) + "\n")
                files += 1
    return files


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="data/fixtures/synthetic")
    a = ap.parse_args()
    root = Path(a.out)
    if root.exists():
        shutil.rmtree(root)
    made = {}
    cases = (("positive", dict(seam_sensitive=True, equal_mean=True)),
             ("null", dict(seam_sensitive=False, equal_mean=True)),
             ("varying-mean", dict(seam_sensitive=True, equal_mean=False)),
             # The seam effect is shrunk far below the specimen-to-specimen scatter, so the
             # honest answer is that the study cannot resolve it: INCONCLUSIVE, never equivalence.
             ("underpowered", dict(seam_sensitive=True, equal_mean=True, effect_scale=0.02,
                                   noise_W=3.0)))
    for case, kw in cases:
        d = root / case; d.mkdir(parents=True)
        made[case] = build_case(d, **kw)

    d = root / "missing-data"; d.mkdir(parents=True)
    rec = run_record("SSY-SYNTH", "SPEC-MD", 1, "R-MD", "uniform", "uniform",
                     1000.0, 0.0, 0, 0.0, 0.0, 4.0, 60.0)
    rec["clearance_field"]["c_um"][5] = None                 # walled sample with no value
    (d / "missing.json").write_text(json.dumps(rec, indent=1) + "\n"); made["missing-data"] = 1

    d = root / "unit-error"; d.mkdir(parents=True)
    rec = run_record("SSY-SYNTH", "SPEC-UE", 1, "R-UE", "uniform", "uniform",
                     1000.0, 0.0, 0, 0.0, 0.0, 4.0, 60.0)
    rec["units"]["c_um"] = "mm"                              # declared in the wrong unit
    rec["clearance_field"]["c_um"] = [None if v is None else v / 1000.0
                                      for v in rec["clearance_field"]["c_um"]]
    (d / "unit-error.json").write_text(json.dumps(rec, indent=1) + "\n"); made["unit-error"] = 1

    (root / "README.md").write_text(
        "# Synthetic fixtures\n\n**SYNTHETIC TEST DATA - NOT EVIDENCE.**\n\n"
        "Nothing here was measured. Every value comes from the closed-form generator in\n"
        "`scripts/make_synthetic_fixtures.py`, so the correct answer is known before the pipeline\n"
        "runs. These exist only to fix the analysis before any real data exists, which is the\n"
        "point of backlog task SSY-05.\n\n"
        "| case | what it is for |\n| --- | --- |\n"
        "| `positive` | equal mean clearance throughout, the design the project actually proposes; power depends on seam count and total opening beyond mean clearance |\n"
        "| `varying-mean` | the same generator with mean clearance deliberately varied, so the clearance-slope baseline is identifiable and both baseline forms are exercised |\n"
        "| `null` | equal mean clearance and no seam sensitivity at all; the defect-aware model must NOT be credited |\n"
        "| `missing-data` | a walled sample carries no clearance value; ingestion must refuse it |\n"
        "| `unit-error` | the clearance channel is declared in millimetres; ingestion must refuse it |\n\n"
        "| `underpowered` | a real but tiny seam effect buried under specimen scatter; the honest verdict is INCONCLUSIVE, not equivalence and not a null |\n\n"
        "Specimen and run scatter are deterministic pseudo-random offsets, so the files are\n"
        "reproducible while the specimen-first scoring and the uncertainty on the improvement are\n"
        "actually exercised.\n\n"
        "Regenerate with `python scripts/make_synthetic_fixtures.py`.\n")
    print(json.dumps(made, indent=1))


if __name__ == "__main__":
    main()
