#!/usr/bin/env python3
"""Audit the Study A candidate design and generate its prose table from the data file.

The JSON file is the single source. Everything a reader sees is derived from it here, so a
row cannot be edited in prose without the audit moving. The audit reports rank, conditioning
under a stated scaling convention, and which effects are invisible at the training locations.

Nothing in this file authorises a run. The design is dimensionless: physical levels are open
and the status stays CANDIDATE_DESIGN_AUDITED until they are registered and frozen.
"""
import argparse
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / "data/study-a/candidate-design-2026-09-25.json"

# Order matters: it is the declared basis and the reported coefficient order.
TERMS = ("1", "x", "y", "z", "x*y", "x*z", "y*z", "x^2", "y^2", "z^2")


def model_matrix(points):
    """Rows of the declared quadratic basis, in the declared column order."""
    out = []
    for p in points:
        x, y, z = float(p["x"]), float(p["y"]), float(p["z"])
        out.append([1.0, x, y, z, x * y, x * z, y * z, x * x, y * y, z * z])
    return np.asarray(out, dtype=float)


def audit(design):
    """Rank, conditioning and the effects the training locations cannot see."""
    train = design["training"]
    X = model_matrix(train)
    sv = np.linalg.svd(X, compute_uv=False)
    rank = int(np.linalg.matrix_rank(X))
    triple = sorted({float(p["x"]) * float(p["y"]) * float(p["z"]) for p in train})
    hold = model_matrix(design["holdouts"])
    hold_triple = [float(p["x"]) * float(p["y"]) * float(p["z"]) for p in design["holdouts"]]
    return dict(
        rows=X.shape[0], columns=X.shape[1], rank=rank,
        full_rank=rank == X.shape[1],
        condition_number=float(sv[0] / sv[-1]),
        smallest_singular_value=float(sv[-1]),
        residual_degrees_of_freedom=X.shape[0] - X.shape[1],
        residual_dof_note="surrogate residual only; not pure error and not physical replication",
        scaling_convention="coded factors as given, no further rescaling",
        three_way_interaction_values_at_training=triple,
        three_way_interaction_invisible=triple == [0.0],
        three_way_interaction_values_at_holdouts=hold_triple,
        holdouts_expose_three_way=any(v != 0.0 for v in hold_triple),
        holdout_rank_if_fitted=int(np.linalg.matrix_rank(hold)),
    )


def constraint_report(design):
    """Which geometric constraints can be checked now, and which need physical inputs."""
    open_inputs = design["physical_inputs_open"]
    return dict(
        checkable_now=[],
        blocked_on_physical_inputs=design["constraints"],
        reason=("Every constraint is stated in F and s, whose ranges (%s) are unresolved. "
                "None can be evaluated until those are registered." % ", ".join(open_inputs)),
    )


def table(points, kind):
    lines = ["| id | x | y | z | role |", "| --- | --- | --- | --- | --- |"]
    for p in points:
        lines.append("| %s | %g | %g | %g | %s |" % (p["id"], p["x"], p["y"], p["z"], kind))
    return "\n".join(lines)


def render(design, a):
    L = ["<!-- Generated by scripts/study_a_design.py from",
         "     data/study-a/candidate-design-2026-09-25.json. Do not edit by hand. -->",
         "", "# Study A candidate design", "",
         "**Status: %s.** %s" % (design["status"], design["status_note"]), "",
         "Structure: %s." % design["structure"], "",
         "## Factor coding", ""]
    for k, v in design["factors"].items():
        L.append("- **%s** maps %s. Coding `%s`." % (k, v["maps"], v["coding"]))
        if "caution" in v:
            L.append("  - %s" % v["caution"])
    L += ["", "Derived: %s." % design["derived"], "",
          "Open physical inputs: %s. Until these are registered the design stays dimensionless."
          % ", ".join("`%s`" % i for i in design["physical_inputs_open"]), "",
          "## Constraints", ""]
    L += ["- %s" % c for c in design["constraints"]]
    L += ["", "None can be evaluated yet. %s" % constraint_report(design)["reason"], "",
          "## Model basis", "",
          "Declared columns in order: %s." % ", ".join("`%s`" % t for t in TERMS), "",
          "## Training locations", "", table(design["training"], "training"), "",
          "## Reserved holdouts", "", table(design["holdouts"], "holdout"), "",
          design["holdout_note"], "", "## Controls", ""]
    L += ["- **%s** %s" % (c["id"], c["label"]) for c in design["controls"]]
    L += ["", design["controls_note"], "", "Run accounting: %s" % design["run_accounting"], "",
          "## Numerical audit", ""]
    L += ["| quantity | value |", "| --- | --- |"]
    for k in ("rows", "columns", "rank", "full_rank", "condition_number",
              "smallest_singular_value", "residual_degrees_of_freedom"):
        v = a[k]
        L.append("| %s | %s |" % (k.replace("_", " "), "%.6f" % v if isinstance(v, float) else v))
    L += ["", "Scaling convention: %s." % a["scaling_convention"],
          "", "Residual degrees of freedom: %s." % a["residual_dof_note"], "",
          "## What this design cannot see", ""]
    L += ["- %s" % l for l in design["limits"]]
    L += ["", "The three-way interaction is %s at every training location, and takes %s at the "
          "holdouts, so those rows are what would expose it."
          % ("zero" if a["three_way_interaction_invisible"] else "non-zero",
             ", ".join("%g" % v for v in a["three_way_interaction_values_at_holdouts"])), ""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify the generated document is current")
    ap.add_argument("--out", default="docs/specs/research-programme/study-a-candidate-design.md")
    args = ap.parse_args()

    design = json.loads(DESIGN.read_text())
    a = audit(design)
    text = render(design, a) + "\n"
    dest = ROOT / args.out
    if args.check:
        if not dest.exists() or dest.read_text() != text:
            print("stale: regenerate with python scripts/study_a_design.py", file=sys.stderr)
            return 1
        if not a["full_rank"]:
            print("design is rank deficient", file=sys.stderr)
            return 1
        print("design document current; rank %d, condition %.6f" % (a["rank"], a["condition_number"]))
        return 0
    dest.write_text(text)
    print("wrote %s (rank %d, condition %.6f)" % (args.out, a["rank"], a["condition_number"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
